from .resnet import *
from .autoencoder import *
from .convnext import *
from .deeponet import *
from .CoDANO import *
from .FNO import *
from .unet import *
from .ITNet import *
from .LNO import *
from .transolver import  *
